### ISSUE TITLE
Clean up common workflow action google-cloud-setup

### ISSUE THREAD

**Issue by katyamust** [hagaltech/common-workflows#14]
google-cloud -setup common acton

```
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.gcp_credentials }}'

```

this action uses input from the caller

```
      - name: Set up Cloud SDK
         uses: 'hagaltech/common-workflows/setup-gcloud-sdk@main'
         with:
             gcp_credentials: ${{ secrets.GCP_SA_KEY }}
```

however GCP_SA_KEY is set globally for the org and might  send ti directly  to  common action and then remove from all the callers.

This would simplify workflow dependencies

WDYT @tordf @andreavs @jacob-hagal ?
